spring.datasource.url=jdbc:postgresql://dpg-d7s6edhkh4rs73f616dg-a.oregon-postgres.render.com:5432/campus_db_ztp0
spring.datasource.username=campus_db_ztp0_user
spring.datasource.password=2ws1eCmz0mALm3Q5bsvdcRgECALcp8UT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true